version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 1
    
    # When you *do* notify us, group all updates into a single PR,
	# but only major updates, not patches and minor changes.
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "major"
    
    # Completely ignore these packages
    ignore:
      - dependency-name: "coverage"
      - dependency-name: "ipython"
      - dependency-name: "nbconvert"
      - dependency-name: "jupyter"
      - dependency-name: "pylint"
      - dependency-name: "ruff"
      - dependency-name: "sphinx"

      # Ignore minor and patch updates for everything else
      - dependency-name: "*"
        update-types: ["version-update:semver-minor", "version-update:semver-patch"]

    # Only security updates
    allow:
      - dependency-type: "all"
