[tool.semantic_release.branches.main]
match = "(main|master|release/v1)"
prerelease_token = "rc"
prerelease = false

[tool.semantic_release]
version_variables = [
    "tradedangerous/version.py:__version__",
]
