# .github/ISSUE_TEMPLATE/bug_report.yml
name: Bug report
description: Report a reproducible problem in the TD V2 fork
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        If using CLI, please ensure your Trade Dangerous is up to date with `pip install --upgrade tradedangerous` before submitting a report.
        If using GUI, please make sure you are using the latest available windows installer.

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Clear description of the bug and expected behaviour.
    validations:
      required: true

  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Exact steps/commands, dataset, config, and branch if relevant.
      render: markdown
    validations:
      required: true

  - type: dropdown
    id: db
    attributes:
      label: Backend
      options:
        - SQLite
        - MariaDB
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / output
      description: |
        Paste relevant logs, error messages, or tracebacks. Please try to use fenced code blocks.

        CLI: Append `-vvvwww` to the original `trade` command and provide the output below. For larger logs (20+ lines), please upload them to [gist](https://gist.github.com/) and provide the gist link here.

        GUI:Crash logs can be found in `%LOCALAPPDATA%\TradeDangerous\logs`. Please paste the contents of the relevant crash log.
      render: shell
    validations:
      required: true

  - type: textarea
    id: env
    attributes:
      label: Environment
      description: OS, Python version, how installed, and any notable config.
