
"""Auto-generated by Alembic.

Revision ID: 5d63cdbddc1f
Revises: 
Create Date: 2025-08-20 15:51:34.767765+00:00

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '5d63cdbddc1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Added',
    sa.Column('added_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('added_id', name=op.f('pk_Added')),
    sa.UniqueConstraint('name', name=op.f('uq_Added__name'))
    )
    op.create_table('Category',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.PrimaryKeyConstraint('category_id', name=op.f('pk_Category'))
    )
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.create_index('idx_category_by_name', ['name'], unique=False)

    op.create_table('ExportControl',
    sa.Column('id', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('last_full_dump_time', mysql.DATETIME(fsp=6), nullable=False),
    sa.Column('last_reset_key', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ExportControl'))
    )
    op.create_table('Ship',
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ship_id', name=op.f('pk_Ship'))
    )
    op.create_table('StationItem_staging',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('demand_price', sa.Integer(), nullable=False),
    sa.Column('demand_units', sa.Integer(), nullable=False),
    sa.Column('demand_level', sa.Integer(), nullable=False),
    sa.Column('supply_price', sa.Integer(), nullable=False),
    sa.Column('supply_units', sa.Integer(), nullable=False),
    sa.Column('supply_level', sa.Integer(), nullable=False),
    sa.Column('modified', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('from_live', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('station_id', 'item_id', name=op.f('pk_StationItem_staging'))
    )
    with op.batch_alter_table('StationItem_staging', schema=None) as batch_op:
        batch_op.create_index('idx_sistaging_stn_itm', ['station_id', 'item_id'], unique=False)

    op.create_table('Upgrade',
    sa.Column('upgrade_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('class', sa.Integer(), nullable=False),
    sa.Column('rating', sa.CHAR(length=1), nullable=False),
    sa.Column('ship', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('upgrade_id', name=op.f('pk_Upgrade'))
    )
    op.create_table('Item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('ui_order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('avg_price', sa.Integer(), nullable=True),
    sa.Column('fdev_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['Category.category_id'], name=op.f('fk_Item__category_id__Category'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('item_id', name=op.f('pk_Item'))
    )
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.create_index('idx_item_by_category', ['category_id'], unique=False)
        batch_op.create_index('idx_item_by_fdevid', ['fdev_id'], unique=False)

    op.create_table('System',
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('pos_x', sa.Float(), nullable=False),
    sa.Column('pos_y', sa.Float(), nullable=False),
    sa.Column('pos_z', sa.Float(), nullable=False),
    sa.Column('added_id', sa.Integer(), nullable=True),
    sa.Column('modified', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['added_id'], ['Added.added_id'], name=op.f('fk_System__added_id__Added'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('system_id', name=op.f('pk_System'))
    )
    with op.batch_alter_table('System', schema=None) as batch_op:
        batch_op.create_index('idx_system_by_name', ['name'], unique=False)
        batch_op.create_index('idx_system_by_pos', ['pos_x', 'pos_y', 'pos_z', 'system_id'], unique=False)

    op.create_table('Station',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('system_id', sa.Integer(), nullable=False),
    sa.Column('ls_from_star', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('blackmarket', sa.Enum('Y', 'N', '?', name='tri_state'), server_default=sa.text("'?'"), nullable=False),
    sa.Column('max_pad_size', sa.Enum('S', 'M', 'L', '?', name='pad_size'), server_default=sa.text("'?'"), nullable=False),
    sa.Column('market', sa.Enum('Y', 'N', '?', name='tri_state'), server_default=sa.text("'?'"), nullable=False),
    sa.Column('shipyard', sa.Enum('Y', 'N', '?', name='tri_state'), server_default=sa.text("'?'"), nullable=False),
    sa.Column('outfitting', sa.Enum('Y', 'N', '?', name='tri_state'), server_default=sa.text("'?'"), nullable=False),
    sa.Column('rearm', sa.Enum('Y', 'N', '?', name='tri_state'), server_default=sa.text("'?'"), nullable=False),
    sa.Column('refuel', sa.Enum('Y', 'N', '?', name='tri_state'), server_default=sa.text("'?'"), nullable=False),
    sa.Column('repair', sa.Enum('Y', 'N', '?', name='tri_state'), server_default=sa.text("'?'"), nullable=False),
    sa.Column('planetary', sa.Enum('Y', 'N', '?', name='tri_state'), server_default=sa.text("'?'"), nullable=False),
    sa.Column('type_id', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('modified', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['system_id'], ['System.system_id'], name=op.f('fk_Station__system_id__System'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('station_id', name=op.f('pk_Station'))
    )
    with op.batch_alter_table('Station', schema=None) as batch_op:
        batch_op.create_index('idx_station_by_name', ['name'], unique=False)
        batch_op.create_index('idx_station_by_system', ['system_id'], unique=False)

    op.create_table('RareItem',
    sa.Column('rare_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('max_allocation', sa.Integer(), nullable=True),
    sa.Column('illegal', sa.Enum('Y', 'N', '?', name='tri_state'), server_default=sa.text("'?'"), nullable=False),
    sa.Column('suppressed', sa.Enum('Y', 'N', '?', name='tri_state'), server_default=sa.text("'?'"), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['Category.category_id'], name=op.f('fk_RareItem__category_id__Category'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['Station.station_id'], name=op.f('fk_RareItem__station_id__Station'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('rare_id', name=op.f('pk_RareItem')),
    sa.UniqueConstraint('name', name='uq_rareitem_name')
    )
    op.create_table('ShipVendor',
    sa.Column('ship_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('modified', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['ship_id'], ['Ship.ship_id'], name=op.f('fk_ShipVendor__ship_id__Ship'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['Station.station_id'], name=op.f('fk_ShipVendor__station_id__Station'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ship_id', 'station_id', name=op.f('pk_ShipVendor'))
    )
    with op.batch_alter_table('ShipVendor', schema=None) as batch_op:
        batch_op.create_index('idx_shipvendor_by_station', ['station_id'], unique=False)

    op.create_table('StationItem',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('demand_price', sa.Integer(), nullable=False),
    sa.Column('demand_units', sa.Integer(), nullable=False),
    sa.Column('demand_level', sa.Integer(), nullable=False),
    sa.Column('supply_price', sa.Integer(), nullable=False),
    sa.Column('supply_units', sa.Integer(), nullable=False),
    sa.Column('supply_level', sa.Integer(), nullable=False),
    sa.Column('modified', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('from_live', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['Item.item_id'], name=op.f('fk_StationItem__item_id__Item'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['station_id'], ['Station.station_id'], name=op.f('fk_StationItem__station_id__Station'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('station_id', 'item_id', name=op.f('pk_StationItem'))
    )
    with op.batch_alter_table('StationItem', schema=None) as batch_op:
        batch_op.create_index('si_fromlive_stn_itm', ['from_live', 'station_id', 'item_id'], unique=False)
        batch_op.create_index('si_itm_dmdpr', ['item_id', 'demand_price'], unique=False)
        batch_op.create_index('si_itm_suppr', ['item_id', 'supply_price'], unique=False)
        batch_op.create_index('si_modified', ['modified'], unique=False)

    op.create_table('UpgradeVendor',
    sa.Column('upgrade_id', sa.Integer(), nullable=False),
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('modified', mysql.DATETIME(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['Station.station_id'], name=op.f('fk_UpgradeVendor__station_id__Station'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['upgrade_id'], ['Upgrade.upgrade_id'], name=op.f('fk_UpgradeVendor__upgrade_id__Upgrade'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('upgrade_id', 'station_id', name=op.f('pk_UpgradeVendor'))
    )
    with op.batch_alter_table('UpgradeVendor', schema=None) as batch_op:
        batch_op.create_index('idx_vendor_by_station_id', ['station_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('UpgradeVendor', schema=None) as batch_op:
        batch_op.drop_index('idx_vendor_by_station_id')

    op.drop_table('UpgradeVendor')
    with op.batch_alter_table('StationItem', schema=None) as batch_op:
        batch_op.drop_index('si_modified')
        batch_op.drop_index('si_itm_suppr')
        batch_op.drop_index('si_itm_dmdpr')
        batch_op.drop_index('si_fromlive_stn_itm')

    op.drop_table('StationItem')
    with op.batch_alter_table('ShipVendor', schema=None) as batch_op:
        batch_op.drop_index('idx_shipvendor_by_station')

    op.drop_table('ShipVendor')
    op.drop_table('RareItem')
    with op.batch_alter_table('Station', schema=None) as batch_op:
        batch_op.drop_index('idx_station_by_system')
        batch_op.drop_index('idx_station_by_name')

    op.drop_table('Station')
    with op.batch_alter_table('System', schema=None) as batch_op:
        batch_op.drop_index('idx_system_by_pos')
        batch_op.drop_index('idx_system_by_name')

    op.drop_table('System')
    with op.batch_alter_table('Item', schema=None) as batch_op:
        batch_op.drop_index('idx_item_by_fdevid')
        batch_op.drop_index('idx_item_by_category')

    op.drop_table('Item')
    op.drop_table('Upgrade')
    with op.batch_alter_table('StationItem_staging', schema=None) as batch_op:
        batch_op.drop_index('idx_sistaging_stn_itm')

    op.drop_table('StationItem_staging')
    op.drop_table('Ship')
    op.drop_table('ExportControl')
    with op.batch_alter_table('Category', schema=None) as batch_op:
        batch_op.drop_index('idx_category_by_name')

    op.drop_table('Category')
    op.drop_table('Added')
    # ### end Alembic commands ###