#! /usr/bin/env bash
# Usage: tdimad [... trade.py options]
#
# Downloads and imports data from maddavo

. "${TRADEDIR:-.}/config.sh"

cmd="${TRADEPY} import --plug=maddavo $*"
echo \$ $cmd
eval "$cmd"
